#!/bin/bash
set -Eeuo pipefail
# set_secrets_from_dev_vars

if ! [ -f ".dev.vars" ]; then
	echo "File '.dev.vars' not found"
	exit 1
fi

IFS="="
while read -rs KEY VALUE; do
	# sets secrets to worker automatically
	if [ -n "$KEY" ]; then
		echo "$VALUE" | yarn wrangler secret put "$KEY"
	fi
done <.dev.vars

# set secrets to github (if CLI is found)
if command -v gh 1> /dev/null && [[ -n "$(git remote -v)" ]]; then
	gh secret set -f .dev.vars
fi
